### ISSUE TITLE
State parameter could not be verified

### ISSUE THREAD

**Issue by skion** [AuthentiqID/wordpress-authentiq#1]
The plug-in occasionally displays the following message:

> The Authentiq state parameter can not be verified. This may be due to this page being cached by another WordPress plugin. Please refresh your page and try again.

And indeed, in that case there appears to be a mismatch between the state value in the browser's cookie and the state that was provided to Authentiq Connect.

**Comment by ziogaschr** [comment]
This has been fixed and released already to the [plugin directory](https://wordpress.org/plugins/authentiq/) as version 1.0.4
